name: 錯誤回報 / Bug report
description: Create a report to help us improve
title: '[Bug] '
labels: ['bug']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: 預期行為 / Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what is the behavior you expected to see?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
       1. Go to '...'
       2. Click on '....'
       3. Scroll down to '....'
       4. See error
  - type: textarea
    id: screenshots
    attributes:
      label: 螢幕截圖 / Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: input
    id: occurrence-time
    attributes:
      label: Time of occurrence
      description: 請提供錯誤發生的時間（如果記得的話）/ Please provide when the error occurred (if you remember).
      placeholder: ex. 2026/01/01 09:00
    validations:
      required: false
